apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
  - port: 33060
    targetPort: 33060
    nodePort: 30307
  selector:
    app: mysql
